version: '3.8'
services:
  threestudio:
    build: .
    container_name: threestudio
    runtime: nvidia
    shm_size: "4g"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/workspace/
    stdin_open: true
    tty: true
